name: Constructorator Field
favicon: null
layout_spectrum: 0.62284
typography_spectrum: 0.472
title: Constructorator Field
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1ca2dc'
    - '#ffffff'
    - '#3a3a3c'
    - '#558eb2'
    - '#a2d1ee'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.5836208355613053
  rhythmicContrast: 0.5
purpose: []
