name: Constructorator Field
favicon: null
layout_spectrum: 0.09724387945607305
typography_spectrum: 0.0903324163518846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7132808675523847
  lightness: 0.32072174083441496
  saturation: 0.5836208355613053
  rhythmicContrast: 0.7237391800154
purpose: []
